baseURL = 'https://luoli523.github.io/huiwang/'
languageCode = 'zh-cn'
title = '回望灯火阑珊'
theme = 'hugo-book'

# Hugo Book theme configuration
[params]
  BookSearch = true
  BookComments = false
  BookMenuBundle = "menu"
  
  [[params.menuBookBeforeEntry]]
    name = "开始阅读"
    weight = 1
    url = "/docs/"
