name: Deploy to Public Repository

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo (source)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.152.2/hugo_extended_0.152.2_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Build with Hugo
        run: hugo --minify

      - name: Deploy to public repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          external_repository: luoli523/huiwang-pages  # 你的 public 仓库
          publish_dir: ./public
          commit_message: "Update site from private repo"
          cname: false

      - name: Build site URL
        run: echo "Site deployed to: https://luoli523.github.io/huiwang-pages/"

